# Generated by Django 6.0.3 on 2026-03-11 11:58

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=200)),
                ('product_name', models.CharField(blank=True, max_length=100, null=True)),
                ('color', models.CharField(blank=True, max_length=25, null=True)),
                ('memory', models.CharField(blank=True, max_length=25, null=True)),
                ('brand', models.CharField(blank=True, max_length=50, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('dis_price', models.IntegerField(blank=True, null=True)),
                ('photos', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, null=True)),
                ('prodcut_code', models.CharField(blank=True, max_length=25, null=True)),
                ('count_feadback', models.IntegerField(blank=True, null=True)),
                ('display_diag', models.CharField(blank=True, max_length=25, null=True)),
                ('display_resol', models.CharField(blank=True, max_length=25, null=True)),
                ('dict_charact', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
